dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
services:
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS microservice;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('pass123') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
