language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
dist: trusty
sudo: required

before_install:
  - mysql -u root --password=""
  - mysql -e "CREATE DATABASE IF NOT EXISTS microservice;"
