dist: trusty
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
services:
  - mysql
before_install:
  - sudo ifconfig
  - mysql -e 'CREATE DATABASE IF NOT EXISTS microservice;'
  - sudo mysqladmin -u root password "pass123"
  - sudo service mysql restart
