dist: trusty
language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS microservice;'
  - sudo mysql -e 'SET PASSWORD FOR "root"@"127.0.0.1" = PASSWORD=("pass123");FLUSH PRIVILEGES;'
  - sudo service mysql restart
